import matplotlib.pyplot as plt
import json
import os

# Path for data files generated by `save_model`
resnet_data_path = os.path.join(os.path.dirname(__file__), "fig3_resnet.json")
mobilenet_data_path = os.path.join(os.path.dirname(__file__), "fig3_mobilenet.json")

# Load data
with open(resnet_data_path, "r") as fin:
  resNetData = json.load(fin)

  resNetEpochs = []
  for i in range(30):
    resNetEpochs.append(i + 1)

with open(mobilenet_data_path, "r") as fin:
  mobileNetData = json.load(fin)

  mobileNetEpochs = []
  for i in range(50):
    mobileNetEpochs.append(i + 1)

# Plot!
fig, axs = plt.subplots(2, 2, figsize=(7, 6))

axs[0, 0].plot(resNetEpochs, resNetData["accuracies"]["train"])
axs[0, 0].plot(resNetEpochs, resNetData["accuracies"]["validation"])
axs[0, 0].set_title("ResNet Accuracies")
axs[0, 0].set(xlabel='Epoch', ylabel='Accuracy')

axs[0, 1].plot(resNetEpochs, resNetData["losses"]["train"])
axs[0, 1].plot(resNetEpochs, resNetData["losses"]["validation"])
axs[0, 1].set_title("ResNet Losses")
axs[0, 1].set(xlabel='Epoch', ylabel='Loss')

l3, = axs[1, 0].plot(mobileNetEpochs, mobileNetData["accuracies"]["train"])
l4, = axs[1, 0].plot(mobileNetEpochs, mobileNetData["accuracies"]["validation"])
axs[1, 0].set_title("MobileNet Accuracies")
axs[1, 0].set(xlabel='Epoch', ylabel='Accuracy')

axs[1, 1].plot(mobileNetEpochs, mobileNetData["losses"]["train"])
axs[1, 1].plot(mobileNetEpochs, mobileNetData["losses"]["validation"])
axs[1, 1].set_title("MobileNet Losses")
axs[1, 1].set(xlabel='Epoch', ylabel='Loss')

axs[0, 1].legend([l3, l4],["Training", "Validation"], loc="upper right")

fig.tight_layout()
plt.ioff()
plt.show()
